### ISSUE TITLE
[Feature] Support for non-empty arrays

### ISSUE THREAD

**Issue by Lightning00Blade** [google/cddlconv#16]
In CDDL the concept of non empty arrays exits via `Type [+text]` will produce an array with at least one text element.
In TypeScript this behavior is achieved with the following example:
```ts
type NonEmptyStringArray = [string, ...string[]]
const array:  NonEmptyStringArray = ['string'];
``` 
In Zod this can be done by using the following chain:
```ts
z.array(context).nonempty()
```

**Comment by jrandolf** [comment]
Fixed in https://github.com/google/cddlconv/pull/17
