### ISSUE TITLE
Newer version of CDDL dependency does not generate types

### ISSUE THREAD

**Issue by OrKoN** [google/cddlconv#6]
We are currently using an older revision in chromium-bidi, locked via https://github.com/google/cddlconv/pull/5

**Comment by OrKoN** [comment]
cc @thiagowfx @Lightning00Blade

**Comment by OrKoN** [comment]
![Uploading Screenshot 2023-08-18 at 09.22.10.png…]()

**Comment by jrandolf** [comment]
Fixed in https://github.com/w3c/webdriver-bidi/pull/512
